run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    ## enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gofumpt
  settings:
    errcheck:
      ignore: ''

formatters:
  settings:
    goimports:
      # Put imports beginning with prefix after 3rd-party packages.
      # It's a comma-separated list of prefixes.
      local-prefixes: github.com/redhatinsights/export-service-go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
