name: ginkgo-test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  ginkgo:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
        name: checkout project
      - name: run ginkgo
        run: |
          go run github.com/onsi/ginkgo/v2/ginkgo -r --procs=1 \
          --compilers=0 --randomize-all --randomize-suites \
          --fail-on-pending --keep-going --cover \
          --coverprofile=cover.profile --race --trace \
          --json-report=report.json --timeout=5m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cover.profile
