name: ginkgo-test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  ginkgo:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      # install ginkgo
      - name: install ginkgo
        run: go get github.com/onsi/ginkgo/ginkgo
      # run ginkgo
      - name: run ginkgo
        run: ginkgo -r -v
